<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

How to change and access the lists arrays or dictionaries.


# 1 Subsetting: Indexing and Slicing

Subsetting is to select date, such as indexing and slicing.

Indexing: picking a single element out of a list/array

slicing: picking a range of elements out of a list/array

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

Since slicing gives us a range of elements, we must specify two indices to indicate where to start and end.

In [3]:
import numpy as np

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)     #This applies to both lists and arrays


x = py_list  
y = np_array

|Syntax|	Result	|	Observed Result|
|-----|-----|--------------|
|`x[0]`	|First element|	'a1'|	
|`x[-1]`|	Last element|	'j10'|	
|`x[0:3]`|	Index 0 to 2|	`['a1','b2','c3']`|	
|`x[1:6]`|	Index 1 to 5	|`['b2','c3','d4','e5','f6']`|
|`x[1:6:2]`	|Index 1 to 5 in steps of 2|	`['b2','d4','f6']`|	
|`x[5:]`|	Index 5 to the end|	`['f6','g7','h8','i9','j10']`|
|`x[:5]`|	Index 0 to 5|	`['a1','b2','c3','d4','e5']`|
|`x[5:2:-1]`|	Index 5 to 3 (i.e., in reverse)|	`['f6','e5','d4']`|
|`x[::-1]`	|Reverses the list	|`['j10','i9','h8',...,'b2','a1']`|

**Syntax reasoning:**

[] within this bracket, there are three components A:B:C.

A: This is the starting slicing element

B: This is the ending slicing element

C: This is the slicing interval

- If A and B are **left open**, it means slice from end of the list.
- If C is -1, it means that slice from back to front.

**Remember slicing in Python can be a bit tricky.**

If you slice with` [i:j`], the slice will start at i and end at j-1, giving you a total of j-i elements.

## 1.2 Arrays only | Subsetting by masking

**Masking only work with numpy arrays!!**

In [8]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])   # Use masking to subset
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
np_array[my_mask]  #ask NumPy to show me only those that are True by
                   # Remember that this is extracting an element from the list. 
                   # We can extract by using index or extract a subset like my_mask

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array[np_array > 3] # We can also use this to make everything easier

array([ 4,  5,  6,  7,  8,  9, 10])

**Interesting examples**

In [14]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'. It is a bitwise not operator
                                         # This is to invert our mask by getting elements that are masked

array([1, 2, 3])

In [15]:
np_array[(np_array > 3) & (np_array < 8)]     # '&' means 'AND'. We can combine one mask with another
                                             # AND will show something only if both masks are true.

array([4, 5, 6, 7])

In [16]:
np_array[(np_array < 3) & (np_array > 8)]   # Note that AND works like a AND gate!! Only if both conditions are true, it gives output.

array([], dtype=int32)

In [17]:
np_array[(np_array < 3) | (np_array > 8)]    # '|' means 'OR'   
                                             # Or gate. 

array([ 1,  2,  9, 10])

- Always use the Bitwise NOT(~), Bitwise OR(|) and Bitwise AND(&) when combining masks with NumPy.
- 
- 
Always use  **brackets**s   to clarify what you are asking the mask to do.

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

The differences between lists and arrays become even more apparent with higher dimensional lists and arrays. Especially when you try indexing and slicing in higher dimensions.

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

**To get a position**

In [20]:
py_list_2d[3]

[4, 'D']

In [19]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

**To get an element of a position**

In [21]:
py_list_2d[3][0]   # Note the syntax differences

4

In [22]:
np_array_2d[3, 0]

'4'

**Slicing**

In [23]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [24]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

**Huge difference!!**

In [25]:
py_list_2d[:3][0]   # For list, it is like you create another list of the first 3 element and then index this new list to get the first element.

[1, 'A']

In [26]:
np_array_2d[:3, 0]  # For array, it is getting the first element of the first three element and placing them into new array

array(['1', '2', '3'], dtype='<U11')

In [27]:
py_list_2d[3:6][0]`

[4, 'D']

In [28]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [29]:
np_array_2d[:, 0]  # If you want all the first element of all elements

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

**One advantage of lists is their ease and efficiency in growing**. 

NumPy arrays are fantastic for fast math operations, **provided you do not change their size.**

In [30]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [32]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [33]:
x=[1]
x+= [2]    # Recall that += is actually just plus, then equal.
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [31]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x    # This is good because it runs exteremely fast

[1, 2, 3, 4]

**Note that append glue exactly what you entered!! (read below)**

In [38]:
x=[1]
x.insert(0,10)
x   # Not taught in lecture but this is interesting.
    # insert have two arguments (A,B)
    # A is the position that you wanna add to (zero index)
    # B is the thing that you wanna add into the list

[10, 1]

**For multiple element**

In [39]:
x = [1, 2, 3]
x += [4, 5, 6]   # Normal
x

[1, 2, 3, 4, 5, 6]

In [40]:
x=[1, 2, 3]
x.extend([4, 5, 6])   # Note that extend is like adding elements from one list to this existing list
x

[1, 2, 3, 4, 5, 6]

In [41]:
x=[1, 2, 3]
x.append([4, 5, 6])  # However, as mentioned. Append glue exactly what you entered into the exising listy
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

Tuples is another data storage structure.

- Truples use () instead of []
- They **cannot be changed** after creation!! (immutable)

In [42]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


**The following will NOT work**

`a[0]=-1`

`a[0]+= [10]`   

**Tuples cannot be changed or added any elements or lists**

## 1.6 Be VERY careful when copying

You should be particularly mindful when making copies of lists and arrays.

- For example, you wanna copya list

In [44]:
x=[1, 2, 3]
y=x           # DON'T do this!   
z=x           # DON'T do this!
             # This is bad because you are just defining x y z as the same list!=

In [46]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()  # Instead, make a copy to ensure it become a new list.

- Note that list is a mutable. Hence by using copy it can create a new list with same content.

-  Note that for tuple, it is immutable. Hence just by defining the typle as another variable, it **automatically** create a new tuple. no need use copy.

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes