<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

This chapter will introduce many ways to store information.

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**python list**

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]  # Learnt in previous chapters, list can use [] to create

**numpy array**


In [28]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])         #.array() is a property of numpy
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**dictionary**

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}    # As learnt before. The thing before : is called a key and the string after the : is called a value.

Two things to note:

- Dictionary elegantly holds the key and value together. However, it actually performs slower than a list(if there are way too many things inside the dictionary)
- For lists and arrays, **the order matters**. I.e. ‘Iron Man’ must be in the same position as ‘Tony Stark’ for things to work.

List and arrays actually have a lot of features that dictionaries don't have. See below.

## 1.2 Accessing data from a list (or array)

![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

- **Remeber that python start with zero**

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [8]:
py_real_names[0]

'Natasha Romanoff'

In [9]:
py_super_names[0]

'Black Widow'

In [10]:
i=0   # The lecturer did this. O well take a look.
print(py_real_names[i], 'is', py_super_names[i]) # remember the comma to separate the string and variable

Natasha Romanoff is Black Widow


- **Reverse index**

In [12]:
py_super_names[-1]   # Reverse indexing is counting from behind to the front. -1 is the last one in the list.

'Doctor Strange'

**Data in lists (and arrays) must be accessed using a zero-based index.**

## 1.3 Accessing data from a dictionary

**Dictionary have a key-value structure. You can access the value using the key.**

Dictionary cannot use index!!!

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [13]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [14]:
superhero_info.keys() # .key is an sttribute of the dictionary to give all keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [16]:
superhero_info.values() #. value is an attribute of the dictionary to give all values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

`2D list is like: [[]   []   []   []]`

`3D list is like: [   [[]   []]      [[]   []]      [[]   []]   ]`

In [20]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],    
                     ['Stephen Strange', 'Doctor Strange']]    

In [19]:
print(py_superhero_info[1])   

['Tony Stark', 'Iron Man']


# 2 Lists vs. Arrays

Lists and arrays have some similarities but more differences.

## 2.1 Size

Both list and array can use len() to see how many elements.

In [21]:
import numpy as np

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],    #list is viewing as an entity, a box of whole things, array is viewing as many different boxes of things inside one
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list   # the reason why we use array is because np has array whereas python got no array
                                        # to create a NEW  # we can use np functions to change the array, but not python itself
                                        # NumPy array

In [15]:
len(py_list_2d)  #len is used to tell u how many things are inside this list

10

In [16]:
len(np_array_2d)

10

In [24]:
np_array_2d.shape   # 10 is the number of things inside the list/array. 2 is the dimension. In this case it is 2D.
                    # shape is not a function!! don't use bracket.

(10, 2)

## 2.2 Arrays are fussy about type

One prominent difference between lists and arrays is that **arrays insist on having only a single data type**; lists are more accommodating.

In [25]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [26]:
py_list  # Note that list can store both a numeric and a string here

[1, 1.5, 'A']

In [27]:
np_array  # Note that np array convert everything to a string!! It can only store one same data type.

array(['1', '1.5', 'A'], dtype='<U32')

we can easily **change type (typecast)** using the ‘hidden’ function **astypes()**. More about this in a later chapter.

## 2.3 Adding a number

Numpy array has this function whereas list doesn't.

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [19]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [20]:
np_array + 10  # Numpy array allow ddition of numbers

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

**DIFFERENT FEATURE!!!**

In [29]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [30]:
py_list_1 + py_list_2    # When adding two list together, you combine their components

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [31]:
np_array_1 + np_array_2  # I view numpy as very mathematical. When adding two numpy, they are added mathematically, with the first number of each array adding each other and so on

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [39]:
py_list*2  # Note that list can be multiplied by creating copies of its element. I don't like to understand it as math. 
#Instead, it is like copy and paste. 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [34]:
np_array*2  # I view numpy as math

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [36]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [38]:
np_array**2   # Ok, at this rate, array is really like math. Afterall numpy is a math program.

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [41]:
py_list == 3     # I think here is asking whether this list is defined as 3. Which is not the question we wanna ask actually.

False

In [42]:
np_array == 3  # Array however, answer whether each element is 3.

array([False, False,  True, False, False])

In [43]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [44]:
np_array > 3    # Similar to previous explaination

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [46]:
sum(py_list)     # sum() is a base Python function

15

In [51]:
np_array.sum()  # Note the difference! In list, sum is a function, in array, sum is a property of numpy

15

In [48]:
max(py_list)     # max() is a base Python function that gives you the maximum number within the list

5

In [50]:
np_array.max()  # Note the difference! In list, max is a function, in array, max is a property of numpy

5

In [53]:
min(py_list)     # min() is a base Python function that gives the smallest number

1

In [55]:
np_array.min()  # Note the difference! In list, min is a function, in array, min is a property of numpy

1

In [56]:
np_array.mean()  # get the mean

3.0

In [58]:
np_array.std()  # get the sd

1.4142135623730951

**(roughly speaking) an operation on a list works on the whole list. In contrast, an operation on an array works on the individual elements of the array.**

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes